New website
arbolista-dev/arbolista-mx pull request #1
Opened 2016-11-03 17:21 UTC by DKbyo

* Add css from template
* Change header
* Change footer
* Add API to retrieve info
* Add Experience boilerplate
* Merge resumes in the same json

Bugs
* Server render doesn't work

2016-11-03 21:23 UTC, Arbolista commented
```js
/* global require */

import i18n from 'i18next';
import LanguagesApi from 'api/languages.api';

function customLoad(url, options, loadComplete, data) {
  let lng = url; // load path must be set to "{{lng}}"
  let languages = {
    en: require('bhf-assets/translations/en.translation')
  };
  console.log("Custom loading of translations ", url, options, loadComplete, data);
  // load the file for given language and namespace
  let lapi = new LanguagesApi();
  lapi.get_translation(languages[lng]).then((result) => {
    console.log("Translation Loaded normally", result);
    return loadComplete(result, {status: 200});
  }).catch((error) => {
      console.log("Translation Loaded with error", error);
    return loadComplete({},  {status: 404});
  });
}

function i18nFactory(environment, directory, provider, callback) {
  let BackendProvider = provider || require('i18next-xhr-backend');
  let path = (environment === 'server') ? `${directory}/../assets/translations/{{lng}}.translation` : "{{lng}}";
  let loader = (environment === 'server') ? undefined : customLoad;

  let options = {
    fallbackLng: 'en',
    lng: 'en',

    // have a common namespace used around the full app
    ns: ['translation'],
    defaultNS: 'translation',

    debug: false,
    /* nsSeparator: false,
    keySeparator: false, */

    interpolation: {
      escapeValue: false // not needed for react!!
    },


    backend: {
      // path where resources get loaded from
      loadPath: path,

      // your backend server supports multiloading
      // /locales/resources.json?lng=de+en&ns=ns1+ns2
      allowMultiLoading: false,
      // allow cross domain requests
      crossDomain: true,

      parse: (data) => data,

      ajax: customLoad
    }
  };

  return i18n
    .use(BackendProvider)
    .init(options, callback);

}


export default i18nFactory;


```

2016-11-03 21:24 UTC, Arbolista commented
se usa: http://i18next.com/

2016-11-07 20:00 UTC, manue1 requested changes
You have missed adding `webpack-node-externals` as a dependency.

Also please move all production-relevant packages to dependencies rather than dev. I guess there's just `webpack-dev-server` that's dev-only.

2016-11-07 20:00 UTC, manue1 commented on server/config/production/server.js
> +      server.app.use('/assets', express.static(path.resolve(__dirname, '../assets')));
Doesn't this already get set correctly in server.config() ?

2016-11-07 20:00 UTC, manue1 commented on server/config/production/server.js
>          console.info(`App is now running on ${os.hostname()}`);
We'll probably always have it running on localhost, so better
```console.info(`App is now running on http://localhost:${APP_PORT}`);```

2016-11-07 20:00 UTC, manue1 commented on shared/components/sections/team/team.rt.html
> -                <a class="link-mask" onClick="{this.goToMember.bind(this, memberIndex)}"></a>
Could you please also remove the method from the component? :grimacing:

2016-11-09 18:11 UTC, DKbyo commented on server/config/production/server.js
> +      server.app.use('/assets', express.static(path.resolve(__dirname, '../assets')));
You're right, I forgot delete this, when I setup the production server correctly

2016-11-09 18:11 UTC, DKbyo commented on server/config/production/server.js
>          console.info(`App is now running on ${os.hostname()}`);
Done!

2016-11-09 18:11 UTC, DKbyo commented on shared/components/sections/team/team.rt.html
> -                <a class="link-mask" onClick="{this.goToMember.bind(this, memberIndex)}"></a>
Don1

2016-11-21 18:36 UTC, merged